spring:
  profiles:
    active: local

---
spring:
  profiles: local

  h2:
    console:
      path: /h2-console:
      enabled: true

  security:
    user:
      password: password
    oauth2:
      resource:
        filter-order: 3
